add nonreentrant to sponsor function
pooltogether/idle-yield-source pull request #1
Opened 2021-06-28 19:37 UTC by kamescg

2021-06-29 15:32 UTC, PierrickGT requested changes

2021-06-29 15:32 UTC, PierrickGT commented on types/factories/ERC20ReturnTrueMockUpgradeable__factory.ts
> +  "0x608060405234801561001057600080fd5b5061067e806100206000396000f3fe608060405234801561001057600080fd5b50600436106100b45760003560e01c80633ba93f26116100715780633ba93f261461015057806370a082311461017257
Add `types` folder to `.gitgnore`

2021-06-30 10:32 UTC, PierrickGT commented on types/factories/ERC20ReturnTrueMockUpgradeable__factory.ts
> +  "0x608060405234801561001057600080fd5b5061067e806100206000396000f3fe608060405234801561001057600080fd5b50600436106100b45760003560e01c80633ba93f26116100715780633ba93f261461015057806370a082311461017257
Since it has been pushed already, you will have to run `git rm -r --cached types`

2021-07-05 23:51 UTC, asselstine approved these changes
Approved with Pierrick's caveat

2021-07-07 10:17 UTC, PierrickGT approved these changes

2021-07-07 10:17 UTC, merged